### ISSUE TITLE
Need to create a model that represents a recommendation

### ISSUE THREAD

**Issue by katydid98** [NYU-DevOps-S18-Recommendations/recommendations#12]
**As a** Service Provider 
**I need** to create a model that represents a recommendation  
**So that** they can be retrieved later and used to recommend products  

**Assumptions:** 
* The model will be kept in the model.py file

**Acceptance Criteria:**
```
Given a product ID#
When a service request for a recommendation is made
Then the model best reflects the relationship between that product and another
```

**Comment by katydid98** [comment]
@jaewhyun @annelai @gau820827 - more practice! In addition to the vagrantfile and the 7 API issues, here's the model issue we also needed to create.

**Comment by jaewhyun** [comment]
what is a model issue?

**Comment by katydid98** [comment]
@jaewhyun I'm not entirely sure yet, but I suspect it's our algorithm for how we are going to determine how two items are related and thus be recommended.  Given a product x, what criteria are we going to implement to determine a relationship with product y.  (My best guess).

**Comment by jaewhyun** [comment]
(still trying to get used to stories representing functionality) Would it be better to add more to the name of the issue with: "...that represents a recommendation" like the prof suggested?

**Comment by katydid98** [comment]
Yea, was wondering the same thing and think would be a good question for professor tomorrow.

**Comment by gau820827** [comment]
@katydid98 I just created milestone 1 and change this issue to that track.
This is a great point! The model part is the most important component of good recommendations, and there are a bunch of algorithms & techniques to achieve that. My guess is that we have to focus on how to delivering our recommendations to customers instead of developing algorithms (That would another course hah). We could check this point with the professor that what should we concentrate on.

**Comment by katydid98** [comment]
@gau820827 sweet! so glad to get your thumbs up.  I'm sure the issue can be better worded, but I can make edits accordingly once we have more guidance tomorrow.

**Comment by katydid98** [comment]
@jaewhyun @gau820827 @annelai Team - I just changed the title of this issue.  I missed the comment on slack where the professor explained how we should title our issues!
