### ISSUE TITLE
I need to UPDATE a recommendation

### ISSUE THREAD

**Issue by jaewhyun** [NYU-DevOps-S18-Recommendations/recommendations#8]
**As a** Service Provider
**I need** a way to update recommendations  
**So that** they can be updated in accordance to new/incoming products

**Assumptions:** 
* A Recommendations database already exists for products
* A product has an existing recommendation/recommendations in the database

**Acceptance Criteria:**
```
Given a product with an id #
When I call PUT  /id /#
Then it would update the recommendations for the product id #
```

**Comment by katydid98** [comment]
@annelai @jaewhyun @gau820827 hey team! I was going to work on this but noticed that service.py already contains the method for this, but no test case.  Trying to investigate how this happened.  Let me know if you have any thoughts.

**Comment by jaewhyun** [comment]
I thought when you wrote the service.py file, you accidentally wrote all the API calls. I think that's why the test case is missing? Am I not understanding your question right?
